#!/usr/bin/env bash
# A simple front end to run all games easily.
# XXX has to be updated as games are added/moved
# XXX most games exit back to the menu, some do not
# XXX a haskell port is welcome, maybe best for portability and power

# All games, in same order as the README: category then submission order.
GAMES=(
prelude/guess1.hs
prelude/pure-doors.hs
base/timing/timing.hs
base/shoot/shoot.hs
base/log2048/log2048.hs
hackage/guess2.hs
hackage/wordle.hs
hackage/ski/ski.hs
hackage/guesscolor/guesscolor.hs
hackage/bulls-n-cows.hs
hackage/hallway-to-hell/hallway-to-hell.hs
hackage/1234-hero/1234-hero.hs
hackage/crappy-flappy/crappy-flappy.hs
)

cat <<HERE
--------------------------------------------------------
                 ___         __                          
|__| _  _|  _||   | . _     / _  _  _  _    | _  _    /| 
|  |(_|_)|((-||   | || )\/  \__)(_||||(-  __)(_||||    | 

--------------------------------------------------------
Here are the entries from HTGJ1, Feb 2023 !
This script can run each game for you, using ghc or stack
(if you don't have these yet, see https://www.haskell.org/get-started).
Most games will return here on exit (others will require CTRL-c).

HERE

RESOLVER=lts-20.10
PS3="** Enter a number to select, or press enter to see the list again: "
select g in "${GAMES[@]}" "Quit"; do
    case "$REPLY" in
    1) "$g";;
    2) "$g";;
    3) "$g";;
    4) "$g";;
    5) runghc "$g";;     # log2048
    6) "$g";;
    7) "$g";;
    8) "$g";;
    9) "$g";;
    10) stack runghc --resolver $RESOLVER --package random "$g";;                # bulls-n-cows  
    11) stack runghc --resolver $RESOLVER --package random --package rio "$g";;  # hallway-to-hell
    12) "$g";;
    13) "$g";;
    $((${#GAMES[@]}+1))) break;;
    *) echo "Invalid selection. Try another one.";continue;;
    esac
done
